//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class aoh_club_theme_topic
    {
        public long id { get; set; }
        public System.DateTime last_post_time { get; set; }
        public System.DateTime publish_time { get; set; }
        public string theme { get; set; }
        public string topic_guid { get; set; }
        public int PostCount { get; set; }
    }
}
