//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AOH_ActivityQuestionDetails
    {
        public AOH_ActivityQuestionDetails()
        {
            this.AOH_ActivityUserAnswersDetails = new HashSet<AOH_ActivityUserAnswersDetails>();
        }
    
        public int ActivityQuestionDetailsID { get; set; }
        public int ActivityInfoID { get; set; }
        public string ActivityQuestionTitle { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual ICollection<AOH_ActivityUserAnswersDetails> AOH_ActivityUserAnswersDetails { get; set; }
    }
}
