//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AOH_RaffleStrategy
    {
        public int StrategyId { get; set; }
        public int RelatedId { get; set; }
        public bool Periodic { get; set; }
        public string UnitOfTime { get; set; }
        public bool MissedPeriodic { get; set; }
        public int RepeatTimesWhenMissed { get; set; }
        public bool ShotPeriodic { get; set; }
        public int RepeatTimesWhenShot { get; set; }
        public bool WheneverPeriodic { get; set; }
        public int RepeatTimesWhenever { get; set; }
        public bool RepeatNoMatterHow { get; set; }
    }
}
