//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AOH_UserSession
    {
        public int UserSessionID { get; set; }
        public string SessionTicket { get; set; }
        public string SessionTicketDigest { get; set; }
        public System.DateTime FirstLoginTime { get; set; }
        public System.DateTime LastLoginTime { get; set; }
        public System.DateTime LastActiveTime { get; set; }
        public string UserName { get; set; }
        public int UserID { get; set; }
        public bool Enable { get; set; }
        public string LoginAppType { get; set; }
        public string LoginAppVer { get; set; }
        public string LoginAppChanel { get; set; }
        public string AutoLoginHints { get; set; }
        public Nullable<System.DateTime> LogoutTime { get; set; }
        public string DisableReason { get; set; }
    }
}
