//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class aoh_usecar_car_register
    {
        public long id { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public string api_support { get; set; }
        public string car_no { get; set; }
        public string car_type { get; set; }
        public string city_id { get; set; }
        public string city_spell { get; set; }
        public string device_token { get; set; }
        public string engine_code { get; set; }
        public string vin { get; set; }
        public string app_type { get; set; }
    }
}
