//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AOH_Activity
    {
        public int ActivityID { get; set; }
        public string ActivityName { get; set; }
        public string ActivityPic { get; set; }
        public int ActivityType { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public string Place { get; set; }
        public int RequiredNum { get; set; }
        public int Ident { get; set; }
        public string ActivityUrl { get; set; }
        public int ReturnType { get; set; }
        public int ActivityNum { get; set; }
        public string ParticipateCondition { get; set; }
        public Nullable<int> Enable { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Creator { get; set; }
        public Nullable<int> ForumID { get; set; }
        public Nullable<int> TopicID { get; set; }
    }
}
