//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AOH_UseCarWelfarePrize
    {
        public int WelfarePrizeID { get; set; }
        public string PublishTime { get; set; }
        public string PrizeType { get; set; }
        public string Status { get; set; }
        public Nullable<int> WinnerUserID { get; set; }
        public string WinnerUserName { get; set; }
        public Nullable<System.DateTime> WinTime { get; set; }
        public string WinnerMobile { get; set; }
        public string WinnerIp { get; set; }
        public int PublishOrder { get; set; }
        public int WelfareID { get; set; }
        public string WinnerRealName { get; set; }
    
        public virtual AOH_UseCarWelfare AOH_UseCarWelfare { get; set; }
    }
}
