//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AOH_SeckillingWinnerContact
    {
        public int ContactId { get; set; }
        public int UserId { get; set; }
        public string UserAddress { get; set; }
        public string UserMobile { get; set; }
        public string UserName { get; set; }
        public string UserAlias { get; set; }
        public string Category { get; set; }
    }
}
