//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AOH_ForumFocusTopic
    {
        public int FocusTopicsID { get; set; }
        public int ForumID { get; set; }
        public int TopicID { get; set; }
        public int DisplayNo { get; set; }
        public string Title { get; set; }
        public string ImageUrl { get; set; }
        public string TopicUrl { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public System.DateTime PublishTime { get; set; }
        public System.DateTime RevokeTime { get; set; }
        public bool Enable { get; set; }
    }
}
