//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AOH_ActivityCoordinateTeam
    {
        public int TeamID { get; set; }
        public int ClubID { get; set; }
        public string ClubName { get; set; }
        public int PeriodID { get; set; }
        public string Teammates { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int CreatorID { get; set; }
        public string CreatorName { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string TeamStatus { get; set; }
        public bool Enable { get; set; }
        public string LogoUrl { get; set; }
    }
}
