//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AOH_UseCarWelfare
    {
        public AOH_UseCarWelfare()
        {
            this.AOH_UseCarWelfarePrize = new HashSet<AOH_UseCarWelfarePrize>();
            this.AOH_UseCarWelfareParticipant = new HashSet<AOH_UseCarWelfareParticipant>();
        }
    
        public int WelfareID { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public string Requirement { get; set; }
        public int ParticipantCount { get; set; }
        public string Address { get; set; }
        public string Detail { get; set; }
        public string Type { get; set; }
        public int DisplayNo { get; set; }
        public string CoverUrl { get; set; }
        public string Name { get; set; }
        public byte Enable { get; set; }
        public bool Recommend { get; set; }
        public string Status { get; set; }
        public string CustomUrl { get; set; }
        public bool AutoIncParticipantCount { get; set; }
    
        public virtual ICollection<AOH_UseCarWelfarePrize> AOH_UseCarWelfarePrize { get; set; }
        public virtual ICollection<AOH_UseCarWelfareParticipant> AOH_UseCarWelfareParticipant { get; set; }
    }
}
