//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AOH_PushBroadcastMessage
    {
        public long PushBroadcastMessageId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string CustomField { get; set; }
        public System.DateTime SendTime { get; set; }
        public bool HasSent { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Creator { get; set; }
        public byte Enable { get; set; }
        public Nullable<System.DateTime> RealSentTime { get; set; }
        public byte TargetPlatform { get; set; }
    }
}
