//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AOH_UtilRecommendApp
    {
        public int UtilRecommendAppID { get; set; }
        public string AppName { get; set; }
        public string AppVersion { get; set; }
        public string AppIcon { get; set; }
        public string Introduction { get; set; }
        public string InstallUrl { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public int DisplayNo { get; set; }
        public string Platform { get; set; }
        public bool Enable { get; set; }
    }
}
