//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AOH_ClubVideoTopic
    {
        public int TopicId { get; set; }
        public int UserId { get; set; }
        public string UserName { get; set; }
        public int ClubId { get; set; }
        public string Content { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string VideoUrl { get; set; }
        public string City { get; set; }
        public int VideoId { get; set; }
        public string VideoCover { get; set; }
        public string VideoTitle { get; set; }
        public bool Enable { get; set; }
        public bool Approval { get; set; }
        public int RealTopicId { get; set; }
    }
}
