//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AOH_UseCarWelfareParticipant
    {
        public int WelfareParticipantID { get; set; }
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string UserMobile { get; set; }
        public int WelfareID { get; set; }
        public System.DateTime JoinWelfareTime { get; set; }
        public string Status { get; set; }
    
        public virtual AOH_UseCarWelfare AOH_UseCarWelfare { get; set; }
    }
}
