//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AOH_ActivityUserAnswersDetails
    {
        public int ActivityUserAnswersDetailsID { get; set; }
        public int ActivityUserID { get; set; }
        public int ActivityInfoID { get; set; }
        public int ActivityQuestionDetailsID { get; set; }
        public Nullable<bool> IsRight { get; set; }
        public string AnswerCode { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual AOH_ActivityInfo AOH_ActivityInfo { get; set; }
        public virtual AOH_ActivityQuestionDetails AOH_ActivityQuestionDetails { get; set; }
        public virtual AOH_ActivityUser AOH_ActivityUser { get; set; }
    }
}
