//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AOH_ActivityCoordinateEvaluation
    {
        public int EvaluationID { get; set; }
        public int TeamID { get; set; }
        public string TeamName { get; set; }
        public string Comment { get; set; }
        public string RewardType { get; set; }
        public Nullable<int> PeriodID { get; set; }
        public Nullable<bool> Enable { get; set; }
    }
}
