//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AOH_ClubRecommendTopicV2
    {
        public long ClubRecommendTopicV2Id { get; set; }
        public int DisplayNo { get; set; }
        public System.DateTime PublishTime { get; set; }
        public System.DateTime RevokeTime { get; set; }
        public string Remark { get; set; }
        public string TopicGuid { get; set; }
        public long TopicId { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Creator { get; set; }
        public byte Enable { get; set; }
        public string Url { get; set; }
    }
}
