//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AOH_ActivityUser
    {
        public AOH_ActivityUser()
        {
            this.AOH_ActivityUserAnswersDetails = new HashSet<AOH_ActivityUserAnswersDetails>();
        }
    
        public int ActivityUserID { get; set; }
        public int ActivityInfoID { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserIp { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> Score { get; set; }
        public string NickName { get; set; }
        public string ActivityUserExtra { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual AOH_ActivityInfo AOH_ActivityInfo { get; set; }
        public virtual ICollection<AOH_ActivityUserAnswersDetails> AOH_ActivityUserAnswersDetails { get; set; }
    }
}
