//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AOH_UseCarRestriction
    {
        public int RestrictionID { get; set; }
        public int CityID { get; set; }
        public byte Priority { get; set; }
        public string DateType { get; set; }
        public string DateValue { get; set; }
        public bool Restrict { get; set; }
        public string CarTailNums { get; set; }
        public string CarTailNumsDesc { get; set; }
        public System.DateTime PublishTime { get; set; }
        public System.DateTime RevokeTime { get; set; }
        public bool Enable { get; set; }
    }
}
