//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AOH_UtilJutuIphoneAdEventLog
    {
        public int AdEventLogId { get; set; }
        public string Idfa { get; set; }
        public System.DateTime AdClickTime { get; set; }
        public Nullable<System.DateTime> AppActiveTime { get; set; }
        public string AppActiveIp { get; set; }
        public string AppVer { get; set; }
        public string AdClickIp { get; set; }
        public int Category { get; set; }
    }
}
