//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class aohEntities : DbContext
    {
        public aohEntities()
            : base("name=aohEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AOH_Activity> AOH_Activity { get; set; }
        public virtual DbSet<AOH_ActivityCoordinateEvaluation> AOH_ActivityCoordinateEvaluation { get; set; }
        public virtual DbSet<AOH_ActivityCoordinatePeriod> AOH_ActivityCoordinatePeriod { get; set; }
        public virtual DbSet<AOH_ActivityCoordinatePoint> AOH_ActivityCoordinatePoint { get; set; }
        public virtual DbSet<AOH_ActivityCoordinateTeam> AOH_ActivityCoordinateTeam { get; set; }
        public virtual DbSet<AOH_ActivityCoordinateTopic> AOH_ActivityCoordinateTopic { get; set; }
        public virtual DbSet<AOH_ActivityInfo> AOH_ActivityInfo { get; set; }
        public virtual DbSet<AOH_ActivityQuestionDetails> AOH_ActivityQuestionDetails { get; set; }
        public virtual DbSet<AOH_ActivityUser> AOH_ActivityUser { get; set; }
        public virtual DbSet<AOH_ActivityUserAnswersDetails> AOH_ActivityUserAnswersDetails { get; set; }
        public virtual DbSet<AOH_ActivityWeixinPrize> AOH_ActivityWeixinPrize { get; set; }
        public virtual DbSet<AOH_ActivityWeixinPrizeUsers> AOH_ActivityWeixinPrizeUsers { get; set; }
        public virtual DbSet<AOH_AutoAttentionUser> AOH_AutoAttentionUser { get; set; }
        public virtual DbSet<AOH_AutoJoinClub> AOH_AutoJoinClub { get; set; }
        public virtual DbSet<AOH_Calllog> AOH_Calllog { get; set; }
        public virtual DbSet<aoh_club_focus_topic> aoh_club_focus_topic { get; set; }
        public virtual DbSet<aoh_club_recommend_theme> aoh_club_recommend_theme { get; set; }
        public virtual DbSet<aoh_club_recommend_topic> aoh_club_recommend_topic { get; set; }
        public virtual DbSet<aoh_club_theme_topic> aoh_club_theme_topic { get; set; }
        public virtual DbSet<AOH_ClubFavoriteClub> AOH_ClubFavoriteClub { get; set; }
        public virtual DbSet<AOH_ClubFavoriteTopic> AOH_ClubFavoriteTopic { get; set; }
        public virtual DbSet<AOH_ClubFreshTopic> AOH_ClubFreshTopic { get; set; }
        public virtual DbSet<AOH_ClubOfficialClub> AOH_ClubOfficialClub { get; set; }
        public virtual DbSet<AOH_ClubRecommendClub> AOH_ClubRecommendClub { get; set; }
        public virtual DbSet<AOH_ClubRecommendClubForFresh> AOH_ClubRecommendClubForFresh { get; set; }
        public virtual DbSet<AOH_ClubRecommendTopicV2> AOH_ClubRecommendTopicV2 { get; set; }
        public virtual DbSet<AOH_ClubThemeGroup> AOH_ClubThemeGroup { get; set; }
        public virtual DbSet<AOH_ClubThemeTopTopic> AOH_ClubThemeTopTopic { get; set; }
        public virtual DbSet<AOH_ClubTopicExtraInfo> AOH_ClubTopicExtraInfo { get; set; }
        public virtual DbSet<AOH_ClubUserTopic> AOH_ClubUserTopic { get; set; }
        public virtual DbSet<AOH_ClubUserTopicFeed> AOH_ClubUserTopicFeed { get; set; }
        public virtual DbSet<AOH_ClubVideoTopic> AOH_ClubVideoTopic { get; set; }
        public virtual DbSet<AOH_ForumFocusTopic> AOH_ForumFocusTopic { get; set; }
        public virtual DbSet<AOH_ForumRecommendTopic> AOH_ForumRecommendTopic { get; set; }
        public virtual DbSet<AOH_ForumTopicExtraInfo> AOH_ForumTopicExtraInfo { get; set; }
        public virtual DbSet<AOH_HuaweiRaffleParticipator> AOH_HuaweiRaffleParticipator { get; set; }
        public virtual DbSet<AOH_ImBlockUser> AOH_ImBlockUser { get; set; }
        public virtual DbSet<AOH_LotteryCarNumber> AOH_LotteryCarNumber { get; set; }
        public virtual DbSet<aoh_push_register> aoh_push_register { get; set; }
        public virtual DbSet<AOH_PushBroadcastMessage> AOH_PushBroadcastMessage { get; set; }
        public virtual DbSet<AOH_RaffleStrategy> AOH_RaffleStrategy { get; set; }
        public virtual DbSet<AOH_RaffleWinnerExtraInfo> AOH_RaffleWinnerExtraInfo { get; set; }
        public virtual DbSet<AOH_SeckillingWinner> AOH_SeckillingWinner { get; set; }
        public virtual DbSet<AOH_SeckillingWinnerArchive> AOH_SeckillingWinnerArchive { get; set; }
        public virtual DbSet<AOH_SeckillingWinnerContact> AOH_SeckillingWinnerContact { get; set; }
        public virtual DbSet<AOH_SocialRecommendUserForFresh> AOH_SocialRecommendUserForFresh { get; set; }
        public virtual DbSet<AOH_TelSegment> AOH_TelSegment { get; set; }
        public virtual DbSet<AOH_TopMan> AOH_TopMan { get; set; }
        public virtual DbSet<AOH_TopManTarget> AOH_TopManTarget { get; set; }
        public virtual DbSet<aoh_usecar_car_register> aoh_usecar_car_register { get; set; }
        public virtual DbSet<AOH_UseCarRestriction> AOH_UseCarRestriction { get; set; }
        public virtual DbSet<AOH_UseCarWelfare> AOH_UseCarWelfare { get; set; }
        public virtual DbSet<AOH_UseCarWelfareParticipant> AOH_UseCarWelfareParticipant { get; set; }
        public virtual DbSet<AOH_UseCarWelfarePrize> AOH_UseCarWelfarePrize { get; set; }
        public virtual DbSet<aoh_user> aoh_user { get; set; }
        public virtual DbSet<AOH_UserCheckInLog> AOH_UserCheckInLog { get; set; }
        public virtual DbSet<AOH_UserExtraInfo> AOH_UserExtraInfo { get; set; }
        public virtual DbSet<AOH_UserFollower> AOH_UserFollower { get; set; }
        public virtual DbSet<AOH_UserSession> AOH_UserSession { get; set; }
        public virtual DbSet<AOH_UtilAppPackage> AOH_UtilAppPackage { get; set; }
        public virtual DbSet<AOH_UtilAppStrategy> AOH_UtilAppStrategy { get; set; }
        public virtual DbSet<AOH_UtilEventLog> AOH_UtilEventLog { get; set; }
        public virtual DbSet<AOH_UtilJutuIphoneAdEventLog> AOH_UtilJutuIphoneAdEventLog { get; set; }
        public virtual DbSet<AOH_UtilRecommendApp> AOH_UtilRecommendApp { get; set; }
        public virtual DbSet<AOH_UtilShortUrl> AOH_UtilShortUrl { get; set; }
        public virtual DbSet<Base_ValueList> Base_ValueList { get; set; }
        public virtual DbSet<CUS_ObdDeviceNotifyInfo> CUS_ObdDeviceNotifyInfo { get; set; }
        public virtual DbSet<CUS_ObdDrivingShare> CUS_ObdDrivingShare { get; set; }
        public virtual DbSet<CUS_ObdUserCar> CUS_ObdUserCar { get; set; }
        public virtual DbSet<CUS_ObdUserInfo> CUS_ObdUserInfo { get; set; }
        public virtual DbSet<F00_ExtenNumner> F00_ExtenNumner { get; set; }
        public virtual DbSet<F00_NumberClass> F00_NumberClass { get; set; }
        public virtual DbSet<F00_ParkCardApplication> F00_ParkCardApplication { get; set; }
        public virtual DbSet<F00_UserApplication> F00_UserApplication { get; set; }
        public virtual DbSet<SYS_RequestStatLog> SYS_RequestStatLog { get; set; }
        public virtual DbSet<SYS_RequestTimeoutLog> SYS_RequestTimeoutLog { get; set; }
        public virtual DbSet<SystemUer> SystemUers { get; set; }
    }
}
