//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base_ValueList
    {
        public int ID { get; set; }
        public string ValueCode { get; set; }
        public string ValueListItemCN { get; set; }
        public string ValueListItemEN { get; set; }
        public string ValueListItemDesCN { get; set; }
        public string ValueListItemDesEN { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string ParentCode { get; set; }
        public string Region { get; set; }
        public Nullable<int> Enable { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Modifier { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> SortNo { get; set; }
        public Nullable<int> Deltag { get; set; }
        public Nullable<int> VersionID { get; set; }
        public Nullable<int> IsSystem { get; set; }
    }
}
