//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUS_ObdDrivingShare
    {
        public int DrivingShareID { get; set; }
        public string ObdUserID { get; set; }
        public System.DateTime DrivingDate { get; set; }
        public byte Score { get; set; }
        public string Message { get; set; }
        public double Mileage { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string ShareGuid { get; set; }
    }
}
