//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class F00_ParkCardApplication
    {
        public int ApplicationId { get; set; }
        public int User400ApplicationId { get; set; }
        public string Username { get; set; }
        public string UserHandy { get; set; }
        public string UserProvince { get; set; }
        public string UserCity { get; set; }
        public string UserAddress { get; set; }
        public System.DateTime ApplicationTime { get; set; }
        public int Status { get; set; }
        public string Remark { get; set; }
    }
}
