//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class F00_UserApplication
    {
        public int ApplicationId { get; set; }
        public string UserCode { get; set; }
        public System.DateTime OperationTime { get; set; }
        public int OperationType { get; set; }
        public string Username { get; set; }
        public string CellphoneLocation { get; set; }
        public string CellphoneNumber { get; set; }
        public string Cellphone400 { get; set; }
        public int Status { get; set; }
        public string Remark { get; set; }
    }
}
