//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_RequestStatLog
    {
        public int LogId { get; set; }
        public string Url { get; set; }
        public string Method { get; set; }
        public string ServerIP { get; set; }
        public double MaxDuration { get; set; }
        public double MinDuration { get; set; }
        public double AvgDuration { get; set; }
        public double MiddleDuration { get; set; }
        public double VarianceDuration { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public int Count { get; set; }
    }
}
