//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_RequestTimeoutLog
    {
        public int LogId { get; set; }
        public string Url { get; set; }
        public string Method { get; set; }
        public System.DateTime RecordTime { get; set; }
        public double Duration { get; set; }
        public int ResponseCode { get; set; }
        public string WebServerIp { get; set; }
        public string QueryString { get; set; }
        public string ClientIP { get; set; }
    }
}
