//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUer
    {
        public int SystemUersID { get; set; }
        public string UersName { get; set; }
        public string Password { get; set; }
        public Nullable<int> Enable { get; set; }
        public string Roles { get; set; }
        public string Mobile { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
    }
}
