//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://aoh.yiche.com/", ConfigurationName="ServiceReference1.UGCSyncServiceSoap")]
    public interface UGCSyncServiceSoap {
        
        // CODEGEN: 命名空间 http://aoh.yiche.com/ 的元素名称 xmlMessage 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://aoh.yiche.com/Send", ReplyAction="*")]
        ConsoleApp.ServiceReference1.SendResponse Send(ConsoleApp.ServiceReference1.SendRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Send", Namespace="http://aoh.yiche.com/", Order=0)]
        public ConsoleApp.ServiceReference1.SendRequestBody Body;
        
        public SendRequest() {
        }
        
        public SendRequest(ConsoleApp.ServiceReference1.SendRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aoh.yiche.com/")]
    public partial class SendRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlMessage;
        
        public SendRequestBody() {
        }
        
        public SendRequestBody(string xmlMessage) {
            this.xmlMessage = xmlMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendResponse", Namespace="http://aoh.yiche.com/", Order=0)]
        public ConsoleApp.ServiceReference1.SendResponseBody Body;
        
        public SendResponse() {
        }
        
        public SendResponse(ConsoleApp.ServiceReference1.SendResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SendResponseBody {
        
        public SendResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UGCSyncServiceSoapChannel : ConsoleApp.ServiceReference1.UGCSyncServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UGCSyncServiceSoapClient : System.ServiceModel.ClientBase<ConsoleApp.ServiceReference1.UGCSyncServiceSoap>, ConsoleApp.ServiceReference1.UGCSyncServiceSoap {
        
        public UGCSyncServiceSoapClient() {
        }
        
        public UGCSyncServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UGCSyncServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UGCSyncServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UGCSyncServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp.ServiceReference1.SendResponse ConsoleApp.ServiceReference1.UGCSyncServiceSoap.Send(ConsoleApp.ServiceReference1.SendRequest request) {
            return base.Channel.Send(request);
        }
        
        public void Send(string xmlMessage) {
            ConsoleApp.ServiceReference1.SendRequest inValue = new ConsoleApp.ServiceReference1.SendRequest();
            inValue.Body = new ConsoleApp.ServiceReference1.SendRequestBody();
            inValue.Body.xmlMessage = xmlMessage;
            ConsoleApp.ServiceReference1.SendResponse retVal = ((ConsoleApp.ServiceReference1.UGCSyncServiceSoap)(this)).Send(inValue);
        }
    }
}
